# MusiCA

## Setup

In [1]:

using RemoteREPL
remoteREPLStarted::Bool = false
if !remoteREPLStarted
  @async serve_repl()
  remoteREPLStarted = true
end

true

#### Yhdistä REPL notebookkiin
`connect_repl()`

#### Hae muuttujia
`x = @remote(x)`  
`a, b = @remote(a,b)`

#### doc
https://c42f.github.io/RemoteREPL.jl/dev/

## Scratch

In [7]:
using CellularAutomata

function conversion(rule, states, radius::Int)
  rule_len = states^(2 * radius + 1) 
  rule_bin = parse.(Int, split(string(rule, base=states), ""))
  rule_bin = vcat(zeros(typeof(rule_bin[1]), rule_len - length(rule_bin)), rule_bin)
  reverse!(rule_bin)
end

function conv2(rule, states, radius::Int)
  rule_len = states^(2 * radius + 1)
  digits(Int64, rule, base=2, pad=rule_len)
end

states = 2
rule = 10
radius = 1
# rule_len = states^(2 * radius + 1)
# rule_bin = parse.(Int, split(string(rule, base=states), ""))
# display(rule_bin)

display(conversion(rule, states, radius))
display(conv2(rule, states, radius))
# d = conv2(110, 2, 1)

8-element Vector{Int64}:
 0
 1
 0
 1
 0
 0
 0
 0

8-element Vector{Int64}:
 0
 1
 0
 1
 0
 0
 0
 0

In [2]:
display(zeros(Bool, 5))



5-element Vector{Bool}:
 0
 0
 0
 0
 0

In [1]:
using Transducers

struct Grid1D
  nstates::Int
  cells::Vector{Int}
end

struct DiscreteCA
  rule::Int
  ruleset::Vector{Int}
  nstates::Int
  radius::Int
end

undigits(d; base=10) = foldr((a, b) -> muladd(base, b, a), d, init=0)

"""
    rule_to_ruleset(rule::Int, nstates::Int = 2, radius::Int = 1)

Return a little-endian vector for the transition rule

```jldoctest
rule_to_ruleset(30)

# output
8-element Vector{Int64}:
 0
 1
 1
 1
 1
 0
 0
 0

```
"""
function rule_to_ruleset(rule::Int, nstates::Int=2, radius::Int=1)
  rule_len = nstates^(2 * radius + 1)
  digits(Int, rule, base=2, pad=rule_len)
end

grid = [0, 0, 1, 0, 0, 1]

# big-endian 00011110
rule = 30


6-element Vector{Int64}:
 0
 0
 1
 0
 0
 1

In [75]:
using Transducers
using StaticArrays


xf_printer(label) = Map() do x
    println(label, ": ", x)
    return x  # just return it as-is
end
function rule_to_ruleset(rule::Int, nstates::Int=2, radius::Int=1)
  rule_len = nstates^(2 * radius + 1)
  rule_to_ruleset(rule, Val(nstates), Val(radius), Val(rule_len))
end

function rule_to_ruleset(rule::Int, ::Val{NStates}, ::Val{Radius}, ::Val{RuleLen})::SVector{RuleLen} where {NStates,Radius,RuleLen}
  SVector{RuleLen,Int}(digits(Int, rule, base=NStates, pad=RuleLen))
end

undigits(d, base=2) = foldr((digit, acc) -> muladd(base, acc, digit), d, init=0)

state = SVector{7,Int}([1, 0, 0, 0, 0, 0, 0])
radius = 1
neighborhood_size = radius * 2 + 1
rule = 110
# 0 1 1 1 0 1 1 0
ruleset = rule_to_ruleset(110)

function evolve(state)
  (state[end-neighborhood_size÷2+1:end], state, state[1:neighborhood_size÷2]) |> 
  Cat() |> 
  Consecutive(neighborhood_size, 1) |>
  # xf_printer("inp") |>
  Map(neighb -> undigits(neighb, 2) + 1) |>
  Map(idx -> ruleset[idx]) |>
  collect |>
  similar_type(state)
end

scopy = state
res = for _ in 1:10
  scopy = evolve(scopy)
end
@show res

# @show undigits(res)

# >3x enemmän allokaatioita
# @time LazyArrays.Vcat(state[end-neighborhood_size÷2+1:end], state, state[1:neighborhood_size÷2]) |> Consecutive(3, 1) |> collect;


inp: (0, 1, 0)
inp: (1, 0, 0)
inp: (0, 0, 0)
inp: (0, 0, 0)
inp: (0, 0, 0)
inp: (0, 0, 0)
inp: (0, 0, 1)
inp: (0, 1, 1)
inp: (1, 1, 0)
inp: (1, 0, 0)
inp: (0, 0, 0)
inp: (0, 0, 0)
inp: (0, 0, 0)
inp: (0, 0, 1)
inp: (0, 1, 1)
inp: (1, 1, 1)
inp: (1, 1, 0)
inp: (1, 0, 0)
inp: (0, 0, 0)
inp: (0, 0, 0)
inp: (0, 0, 1)
inp: (0, 1, 0)
inp: (1, 0, 1)
inp: (0, 1, 1)
inp: (1, 1, 0)
inp: (1, 0, 0)
inp: (0, 0, 0)
inp: (0, 0, 1)
inp: (0, 1, 1)
inp: (1, 1, 1)
inp: (1, 1, 1)
inp: (1, 1, 1)
inp: (1, 1, 0)
inp: (1, 0, 0)
inp: (0, 0, 1)
inp: (0, 1, 0)
inp: (1, 0, 0)
inp: (0, 0, 0)
inp: (0, 0, 1)
inp: (0, 1, 1)
inp: (1, 1, 0)
inp: (1, 0, 1)
inp: (1, 1, 1)
inp: (1, 1, 0)
inp: (1, 0, 0)
inp: (0, 0, 1)
inp: (0, 1, 1)
inp: (1, 1, 1)
inp: (1, 1, 1)
inp: (0, 0, 1)
inp: (0, 1, 1)
inp: (1, 1, 0)
inp: (1, 0, 1)
inp: (0, 1, 0)
inp: (1, 0, 0)
inp: (0, 0, 0)
inp: (0, 0, 1)
inp: (0, 1, 1)
inp: (1, 1, 1)
inp: (1, 1, 1)
inp: (1, 1, 1)
inp: (1, 1, 0)
inp: (1, 0, 0)
inp: (1, 0, 1)
inp: (0, 1, 0)
inp: (1, 0, 0)
inp: (0, 0